### ISSUE TITLE
Multi-gpus parallel error

### ISSUE THREAD

**Issue by mooncakehub** [anhthuan1999/PointCT#4]
I am sorry to bother you again.I met some erros when I run the code on 2 2080ti GPUs. 
I tried to set `find_unused_parameters=True` ，But there will still be problems in the first epoch.
The reason I'm looking up on Google is that some of the parameters are not involved in backpropagation, which doesn't occur when a single gpu is running, but does occur when multiple gpus are parallel.Do you have any good solutions to this?thank you for your reply!
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 42 43 85 86 131 132 174 175 220 221 263 264 306 307 349 350 392 393 438 439 481 482
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

```

**Comment by anhthuan1999** [comment]
Hi~, did you change the multiprocessing_distributed (under Distributed section in config files) into True?

**Comment by mooncakehub** [comment]
yes，it's true ,in config/s3dis.yaml

**Comment by mooncakehub** [comment]
Is it possible that the output of the forward part is not involved in backpropagation, but I didn't find the part in the code about the loss calculation.

**Comment by mooncakehub** [comment]
Is it possible that the output of the forward part is not involved in backpropagation, but I didn't find the part in the code about the loss calculation.

**Comment by anhthuan1999** [comment]
So, how about the batch size train and test? In my experience with 2 gpus, I use batch_size 4 for train and 2 for test.

**Comment by mooncakehub** [comment]
When I use the default settings ：  `find_unused_parameters=True if "transformer" in args.arch else False`
![1710833848301](https://github.com/anhthuan1999/PointCT/assets/138660085/ad747b3f-bc85-4c0d-9240-5e5a464385b8)
when I change it: find_unused_parameters=True
This may have nothing to do with batch size

**Comment by mooncakehub** [comment]
![1710834203142](https://github.com/anhthuan1999/PointCT/assets/138660085/239b2aa6-aea3-426d-a804-a15c72498f85)
![1710834249087](https://github.com/anhthuan1999/PointCT/assets/138660085/6c1c92f4-3c81-4bc0-a0b5-5a413e9ef8c6)

**Comment by mooncakehub** [comment]
![1710834203142](https://github.com/anhthuan1999/PointCT/assets/138660085/433a2540-bc26-4c7f-a706-9c63687e76ed)
![1710834249087](https://github.com/anhthuan1999/PointCT/assets/138660085/910f99f9-bdad-494c-8f65-534458b8d110)
![1710834398267](https://github.com/anhthuan1999/PointCT/assets/138660085/cedfd197-ed3d-4876-ab54-540eb73c47a3)

**Comment by anhthuan1999** [comment]
Hi~, I check similar solution and found this: https://github.com/pytorch/pytorch/issues/43259#issuecomment-1776726607. Could you please test this by working around multiplying parameters with 0.0 and sum with the final loss.

**Comment by mooncakehub** [comment]
thank you for your advice. But how can I find those parameters?my proggramming ability is a little weak. I would appreciate it if you coud remind me further!

**Comment by anhthuan1999** [comment]
You can test it by adding: loss= loss+ 0. * sum(p.sum() for p in model.parameters()) into line 286 in train.py

**Comment by mooncakehub** [comment]
Thank you for your help.You are a serious researcher！however I tried many times, it didn't work too.
![1710851010662](https://github.com/anhthuan1999/PointCT/assets/138660085/5d594988-8b0d-475d-a32e-9354cf885cc6)

**Comment by mooncakehub** [comment]
Thank you for your help.You are a serious researcher！however I tried many times, it didn't work too.I even tried to print the parameters,but it didn't print anything.
![1710851010662](https://github.com/anhthuan1999/PointCT/assets/138660085/0309cf3a-1eb7-4572-b3af-d324e3ffb3ea)

**Comment by anhthuan1999** [comment]
Oh, you have to do that before loss.backward()

**Comment by mooncakehub** [comment]
thank you。 yes ,tried to do  it too

**Comment by mooncakehub** [comment]
thank you。 yes ,tried to do it too.it's didn't work too 😂

**Comment by anhthuan1999** [comment]
For clarification, do you test it using find_unused_parameters=True or find_unused_parameters=False? :D

**Comment by mooncakehub** [comment]
I use the default setting in the train.py (171):  ` find_unused_parameters=True if "transformer" in args.arch else False`.

**Comment by mooncakehub** [comment]
If you have time, you can use ToDesk to view my computer（todesk：474 475 584 i1rbp0iv）.I really want to replicate your work, because my device doesn't support large models, and your work gives me hope.I am a second-year graduate student，Your work is really important to me.It's okay if you don't want to, I'm already grateful for your help！

**Comment by anhthuan1999** [comment]
Unfortunately, I am outside and can't remote into the PC. However, you can test it while using  find_unused_parameters=True.
If the errors appear again, you print the shape of input x in model s3dis.py and try to increase batch_size (around 6 or 8)

**Comment by mooncakehub** [comment]
okay！thank you for your help. i will try.

**Comment by mooncakehub** [comment]
Hello 🤩, I found in the printed network structure that there seems to be a problem with the input dimension of the third Encoder, I guess the input dimension should be 64, not 67, in the code, where should I modify it, can you give advice, thank you for your help！
![1711070432678](https://github.com/anhthuan1999/PointCT/assets/138660085/b299992f-cbf9-4f1d-a61f-1d4dfc4ac8b0)

**Comment by anhthuan1999** [comment]
I don't think this is the problem. The reason behind this number is adding xyz coordinate into previous feature (3+64)

**Comment by mooncakehub** [comment]
Hello，Based on my error,I checked the pytorch source code， I  determine that the cause of the error may be that the array is out of bounds now，I print the shape of the x and don't find the problem, maybe I'm debugging the wrong way.The location of the error is shown in the image, can you debug the code to see if it's the problem。
![1711436972689](https://github.com/anhthuan1999/PointCT/assets/138660085/79b6f36a-bcc3-4445-9c14-3168d81b462a)
![微信图片编辑_20240326150824](https://github.com/anhthuan1999/PointCT/assets/138660085/714594e1-9839-44ac-92b3-cc202f18f6cc)

**Comment by mooncakehub** [comment]
I print the `pox1 pox2`,there were so many nan ,Why is this happening?
![86790e401293e51d3f3d5700c969dc2](https://github.com/anhthuan1999/PointCT/assets/138660085/ac1af8dc-9803-45bf-86c7-a77ffb9ccbb7)

**Comment by mooncakehub** [comment]
I print the `pox1 pox2`（model/s3dis.py:FeaturePropagation),there were so many nan ,Why is this happening?thank you for your help!
![86790e401293e51d3f3d5700c969dc2](https://github.com/anhthuan1999/PointCT/assets/138660085/0421d8a1-383d-415d-8a84-8a41cf29b7be)

**Comment by anhthuan1999** [comment]
Hi, the nan variable is from p or x? because pxo is combination of p, x, o
