### ISSUE TITLE
How to train other datasets,such as Toronto3D or Semantic3D

### ISSUE THREAD

**Issue by mooncakehub** [anhthuan1999/PointCT#6]
Thank you very much for your help and reply !🙇‍ I have already run the code. you trained S3DIS 、ScanNet and STPLS3D datasets,but I want to train Toronto3D and Semantic3D，I condsider that I need to write the code for the pre-processing and data entry part.I know some knowlwdge about pytorch Dataloader,but I don't know data preprocessing,Can you give me some suggestion for data preprocessing? Thank you ! you really help me a lot.

**Comment by mooncakehub** [comment]
Can you publish your pre-training documents?

**Comment by anhthuan1999** [comment]
For these datasets, I see STPLS3D official code also process their data by splitting scenes into smaller blocks and apply these blocks into transformer networks. You can try this approach 😄 For pre-trained checkpoints, I am processing that and will publish soon.
